# Generated by Django 5.0.6 on 2024-06-06 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=280)),
                ('long_description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('hiring_manager', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
