# Generated by Django 5.0.6 on 2024-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="priority",
            field=models.IntegerField(default=10000),
        ),
    ]
