# Generated by Django 5.0.6 on 2024-06-06 19:14

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=150)),
            ],
        ),
    ]
