# Generated by Django 5.0.6 on 2024-06-06 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=150)),
            ],
        ),
    ]
