# Generated by Django 5.0.6 on 2024-06-06 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d71ffdac-7f02-4eb2-8913-7c980552f0b3'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('card_image_url', models.CharField(max_length=500)),
                ('stock_image_url', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=150)),
            ],
        ),
    ]
